services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: ca2p4-db
    ports:
      - "8082:8082"
      - "9092:9092"
    volumes:
      - h2data:/usr/src/app
    networks:
      - ca2net

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: ca2p4-web
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # aponte para o H2 TCP no container "db"
      SPRING_DATASOURCE_URL:  jdbc:h2:tcp://db:9092/~/test
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
      # (opcional) ajuste do Hibernate
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
    networks:
      - ca2net

volumes:
  h2data:

networks:
  ca2net:
    driver: bridge
